// Kopi DB reads — psychographics, brands, authored emails.
// Reads from NEON_DB_URL (kopi's main DB).
//
// The psychographic data lives in brand_embedding_chunks with chunk_type='audience'
// (1000-char descriptions of target customers, generated by kopi's brand enrichment flow).
// We use these directly — no LLM intermediary. The brand's enriched audience IS the persona.

import postgres from "postgres";
import OpenAI from "openai";
import type { Persona, Email, Product } from "./types";

const KOPI_DB_URL = process.env.NEON_DB_URL ?? process.env.KOPI_DATABASE_URL;
if (!KOPI_DB_URL) {
  throw new Error("Set NEON_DB_URL (or KOPI_DATABASE_URL) to kopi's main DB connection string");
}

const sql = postgres(KOPI_DB_URL);

// -----------------------------------------------------------------------------
// Brand discovery
// -----------------------------------------------------------------------------

export type BrandRow = {
  id: string;
  name: string;
  emailCount: number;
  hasAudience: boolean;
};

/** Brands with both an audience psychographic chunk and authored emails. */
export async function listBrandsWithData(limit = 20): Promise<BrandRow[]> {
  const rows = await sql<
    Array<{
      id: string;
      name: string | null;
      brand_name: string | null;
      email_count: string;
    }>
  >`
    SELECT
      b.id,
      b.data->>'name' AS name,
      b.data->>'brandName' AS brand_name,
      (SELECT COUNT(*)
         FROM message_artifact ma
         JOIN message m ON ma.message_id = m.id
         JOIN chat c ON m.chat_id = c.id
         WHERE c.brand_id = b.id) AS email_count
    FROM brands b
    WHERE EXISTS (
      SELECT 1 FROM brand_embedding_chunks
       WHERE brand_id = b.id AND chunk_type = 'audience'
    )
    ORDER BY email_count DESC NULLS LAST
    LIMIT ${limit}
  `;
  return rows.map((r) => ({
    id: r.id,
    name: r.name ?? r.brand_name ?? "(unnamed)",
    emailCount: Number(r.email_count ?? 0),
    hasAudience: true,
  }));
}

// -----------------------------------------------------------------------------
// Psychographic fetch (THE persona content — no LLM hop)
// -----------------------------------------------------------------------------

export type BrandAudience = {
  brandId: string;
  brandName: string;
  audience: string; // ~1000 chars — target customer description
  painPoints?: string;
  dreamsOutcomes?: string;
  brandVoice?: string;
};

/** Pull the audience + supporting psychographic chunks for one brand. */
export async function getBrandAudience(brandId: string): Promise<BrandAudience> {
  const brandRow = await sql<Array<{ name: string | null; brand_name: string | null }>>`
    SELECT data->>'name' AS name, data->>'brandName' AS brand_name
    FROM brands WHERE id = ${brandId}
  `;
  if (brandRow.length === 0) throw new Error(`Brand not found: ${brandId}`);
  const brandName = brandRow[0].name ?? brandRow[0].brand_name ?? "(unnamed)";

  const chunks = await sql<Array<{ chunk_type: string; content: string }>>`
    SELECT chunk_type, content
    FROM brand_embedding_chunks
    WHERE brand_id = ${brandId}
      AND chunk_type IN ('audience', 'pain_points', 'dreams_outcomes', 'brand_voice')
  `;
  const byType = new Map(chunks.map((c) => [c.chunk_type, c.content]));
  const audience = byType.get("audience");
  if (!audience) {
    throw new Error(`Brand ${brandId} has no audience psychographic chunk`);
  }
  return {
    brandId,
    brandName,
    audience,
    painPoints: byType.get("pain_points"),
    dreamsOutcomes: byType.get("dreams_outcomes"),
    brandVoice: byType.get("brand_voice"),
  };
}

/** Build a Persona object from real brand audience psychographics. No LLM call. */
export function audienceToPersona(b: BrandAudience): Persona {
  const sections = [
    `Target audience description (from brand's enrichment):\n${b.audience}`,
    b.painPoints && `What this audience struggles with:\n${b.painPoints}`,
    b.dreamsOutcomes && `What this audience wants to achieve:\n${b.dreamsOutcomes}`,
  ]
    .filter(Boolean)
    .join("\n\n");

  return {
    id: `audience_${b.brandId.slice(0, 12)}`,
    name: `${b.brandName} target customer`,
    age: 0, // audience-level, not individual
    shortBio: `Representative target customer of ${b.brandName}`,
    longProfile: sections,
  };
}

// -----------------------------------------------------------------------------
// Authored email fetch (for A/B selection in UI; CLI uses inline for now)
// -----------------------------------------------------------------------------

export type AuthoredEmail = {
  chatId: string;
  title: string;
  createdAt: Date;
  artifactPreview: string; // first 300 chars of parsed artifact, for selector UI
};

export async function listBrandEmails(brandId: string, limit = 30): Promise<AuthoredEmail[]> {
  const rows = await sql<
    Array<{ chat_id: string; title: string; created_at: Date; parsed: string }>
  >`
    SELECT
      c.id AS chat_id,
      c.title,
      c.created_at,
      ma.parsed
    FROM chat c
    JOIN message m ON m.chat_id = c.id
    JOIN message_artifact ma ON ma.message_id = m.id
    WHERE c.brand_id = ${brandId}
    ORDER BY c.created_at DESC
    LIMIT ${limit}
  `;
  return rows.map((r) => ({
    chatId: r.chat_id,
    title: r.title,
    createdAt: r.created_at,
    artifactPreview: (r.parsed ?? "").slice(0, 300),
  }));
}

/**
 * Pull a real kopi-authored email (by chat id) and shape it as an Email fixture
 * for the simulator. The XML in `message_artifact.raw` is kopi's own block format;
 * we extract: title -> subject, image alt + heading + paragraph text -> bodyText,
 * first non-trivial text line -> preheader.
 */
export async function getEmailFromChat(chatId: string): Promise<Email> {
  const rows = await sql<
    Array<{
      title: string;
      raw: string;
      brand_id: string;
      brand_name: string | null;
      brand_brand_name: string | null;
      preview_text: string | null;
      preview_screenshot_url: string | null;
      screenshot_url: string | null;
    }>
  >`
    SELECT
      c.title,
      ma.raw,
      c.brand_id,
      b.data->>'name' AS brand_name,
      b.data->>'brandName' AS brand_brand_name,
      c.metadata->>'previewText' AS preview_text,
      c.metadata->>'previewScreenshotUrl' AS preview_screenshot_url,
      c.metadata->'generationStatusInfo'->>'screenshotUrl' AS screenshot_url
    FROM chat c
    JOIN message m ON m.chat_id = c.id
    JOIN message_artifact ma ON ma.message_id = m.id
    JOIN brands b ON b.id = c.brand_id
    WHERE c.id = ${chatId}
  `;
  if (rows.length === 0) throw new Error(`No email found for chat ${chatId}`);
  const r = rows[0];
  const brandName = r.brand_name ?? r.brand_brand_name ?? r.brand_id;
  const bodyText = extractTextFromKopiRaw(r.raw);
  // Prefer the kopi-stored previewText (real preheader). Fall back to first body line.
  const preheaderFromBody =
    bodyText
      .split(/\n+/)
      .map((s) => s.trim())
      .find((s) => s.length > 20 && !s.startsWith("[Image:") && !s.startsWith("[Button:"))
      ?.slice(0, 140) ?? "";
  return {
    id: chatId,
    brandId: r.brand_id,
    brandName,
    sender: `${brandName} <hello@${brandName.toLowerCase().replace(/[^a-z0-9]/g, "")}.com>`,
    subject: r.title,
    preheader: r.preview_text ?? preheaderFromBody,
    bodyText,
    previewScreenshotUrl: r.preview_screenshot_url ?? r.screenshot_url ?? undefined,
  };
}

/** Fetch products by their UUIDs (for resolving purchase rows in UI). */
export async function getProductsByIds(ids: string[]): Promise<Product[]> {
  if (ids.length === 0) return [];
  const rows = await sql<
    Array<{
      id: string;
      brand_id: string;
      title: string;
      description: string | null;
      price_cents: number | null;
      thumbnail_url: string | null;
    }>
  >`
    SELECT id, brand_id, title, description, price_cents, thumbnail_url
    FROM brand_products
    WHERE id = ANY(${ids}::uuid[])
  `;
  return rows.map((r) => ({
    id: r.id,
    brandId: r.brand_id,
    name: r.title,
    price: (r.price_cents ?? 0) / 100,
    description: (r.description ?? "").slice(0, 600),
    thumbnailUrl: r.thumbnail_url ?? undefined,
  }));
}

/** Extract plain text from kopi's email block XML. Preserves image alt text + buttons. */
function extractTextFromKopiRaw(raw: string): string {
  return raw
    .replace(/<IMAGE[^>]*?\salt="([^"]*)"[^>]*?\/?>/gi, "\n[Image: $1]\n")
    .replace(/<IMAGE[^>]*?\/?>/gi, "")
    .replace(/<BUTTON[^>]*?>([\s\S]*?)<\/BUTTON>/gi, "\n[Button: $1]\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/[ \t]+/g, " ")
    .replace(/\n\s*\n+/g, "\n\n")
    .trim();
}

// -----------------------------------------------------------------------------
// Author-selected products for an email (round-3 PRIMARY input)
// -----------------------------------------------------------------------------
// At email-creation time, kopi users pick which products to feature. Those
// selections are stored on message.metadata.mediaPlan.products (array of
// product entries with `dbId` joining to brand_products). This is the
// author's intent — strictly preferred over semantic search when available.

export async function getFeaturedProductsForEmail(chatId: string): Promise<Product[]> {
  // 1. Find the brand + the "selected" message for this chat
  const chatRows = await sql<
    Array<{ selected_message_id: string | null; brand_id: string }>
  >`
    SELECT metadata->>'selectedMessageId' AS selected_message_id, brand_id
    FROM chat WHERE id = ${chatId}
  `;
  if (chatRows.length === 0) return [];
  const { selected_message_id, brand_id } = chatRows[0];

  // 2. Pull mediaPlan.products from the selected message (or first if not specified)
  type MsgRow = { products: unknown };
  const msgRows = selected_message_id
    ? await sql<MsgRow[]>`
        SELECT metadata->'mediaPlan'->'products' AS products
        FROM message WHERE id = ${selected_message_id}
      `
    : await sql<MsgRow[]>`
        SELECT metadata->'mediaPlan'->'products' AS products
        FROM message WHERE chat_id = ${chatId}
        ORDER BY id LIMIT 1
      `;
  if (msgRows.length === 0) return [];
  const productsList = msgRows[0].products;
  if (!Array.isArray(productsList) || productsList.length === 0) return [];

  // 3. Extract dbIds (kopi's brand_products.id), preserve author's chosen order
  const dbIds = productsList
    .map((p) => (typeof p === "object" && p && "dbId" in p ? (p as { dbId?: unknown }).dbId : undefined))
    .filter((id): id is string => typeof id === "string");
  if (dbIds.length === 0) return [];

  // 4. Join to brand_products for live product data
  const productRows = await sql<
    Array<{
      id: string;
      title: string;
      description: string | null;
      price_cents: number | null;
      thumbnail_url: string | null;
    }>
  >`
    SELECT id, title, description, price_cents, thumbnail_url
    FROM brand_products
    WHERE id = ANY(${dbIds}::uuid[])
      AND price_cents IS NOT NULL
  `;
  const byId = new Map(productRows.map((r) => [r.id, r]));

  // Preserve author's selection order
  return dbIds
    .map((id) => byId.get(id))
    .filter((r): r is NonNullable<typeof r> => r !== undefined)
    .map((r) => ({
      id: r.id,
      brandId: brand_id,
      name: r.title,
      price: (r.price_cents ?? 0) / 100,
      description: (r.description ?? "").slice(0, 600),
      thumbnailUrl: r.thumbnail_url ?? undefined,
    }));
}

// -----------------------------------------------------------------------------
// Embedding search for products (round-3 FALLBACK input)
// -----------------------------------------------------------------------------
// Matches kopi's embedding setup: text-embedding-3-small (1536 dims).
// Stored in brand_products.embedding (pgvector). We compute a query embedding
// from the email body text and do cosine-distance search.

const openaiClient = new OpenAI();
const EMBEDDING_MODEL = "text-embedding-3-small";

async function getQueryEmbedding(text: string): Promise<number[]> {
  // Truncate aggressively — text-embedding-3-small max is 8192 tokens,
  // an email body is ~1-2k chars and well within limits.
  const trimmed = text.slice(0, 6000);
  const r = await openaiClient.embeddings.create({
    model: EMBEDDING_MODEL,
    input: trimmed,
  });
  return r.data[0].embedding;
}

/**
 * Find the top-N products from a brand that semantically match the given email
 * body text. Returns empty array if the brand has no embedded products (e.g.,
 * synthetic background brands not in kopi DB).
 */
export async function searchProductsForEmail(
  brandId: string,
  emailText: string,
  limit = 3,
): Promise<Product[]> {
  const queryEmb = await getQueryEmbedding(emailText);
  const queryVec = `[${queryEmb.join(",")}]`;
  const rows = await sql<
    Array<{
      id: string;
      title: string;
      description: string | null;
      price_cents: number | null;
      thumbnail_url: string | null;
      similarity: number;
    }>
  >`
    SELECT
      id, title, description, price_cents, thumbnail_url,
      1 - (embedding <=> ${queryVec}::vector) AS similarity
    FROM brand_products
    WHERE brand_id = ${brandId}
      AND embedding IS NOT NULL
      AND price_cents IS NOT NULL
    ORDER BY embedding <=> ${queryVec}::vector
    LIMIT ${limit}
  `;
  return rows.map((r) => ({
    id: r.id,
    brandId,
    name: r.title,
    price: r.price_cents != null ? r.price_cents / 100 : 0,
    description: (r.description ?? "").slice(0, 600),
    thumbnailUrl: r.thumbnail_url ?? undefined,
  }));
}

// -----------------------------------------------------------------------------
// Lifecycle
// -----------------------------------------------------------------------------

export async function closeDb(): Promise<void> {
  await sql.end();
}
